# Generated by Django 5.1.1 on 2025-03-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
