# Generated by Django 5.1.1 on 2025-02-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('cards', '0002_alter_classes_name_alter_grades_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Classe',
        ),
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
        migrations.RenameModel(
            old_name='ParentsStudents',
            new_name='ParentStudent',
        ),
        migrations.RenameModel(
            old_name='Schools',
            new_name='School',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='StudentsClasses',
            new_name='StudentClasse',
        ),
        migrations.RenameModel(
            old_name='StudentsGrades',
            new_name='StudentGrade',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.RenameModel(
            old_name='TeachersClasses',
            new_name='TeacherClasse',
        ),
        migrations.RenameModel(
            old_name='TeachersSubjects',
            new_name='TeacherSubject',
        ),
    ]
