# Generated by Django 5.1.1 on 2025-02-27 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_classes_classe_rename_grades_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.student')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.teacher')),
            ],
        ),
    ]
