# Generated by Django 5.1.1 on 2025-03-12 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_studentschool_teacherschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.teacher'),
        ),
    ]
