# Generated by Django 5.1.1 on 2025-03-12 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_studentgrade_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['value']},
        ),
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='studentclasse',
            name='assignmentDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
