# Generated by Django 5.1.1 on 2025-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_grade_options_alter_studentgrade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
