# Generated by Django 5.1.1 on 2025-03-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_teacher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='year',
        ),
        migrations.AddField(
            model_name='classe',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.school'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='dayType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.school'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='startTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekDay',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='FixedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('duration', models.IntegerField()),
                ('dayType', models.CharField(max_length=50)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.classe')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.teacher')),
            ],
        ),
    ]
