# Generated by Django 5.1.1 on 2025-04-11 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_schedule_year_classe_school_schedule_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedschedule',
            name='dayType',
        ),
        migrations.RemoveField(
            model_name='fixedschedule',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='fixedschedule',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='fixedschedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='fixedschedule',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='fixedschedule',
            name='weekDay',
        ),
        migrations.AddField(
            model_name='fixedschedule',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedschedule',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fixedschedule',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dayType',
            field=models.CharField(choices=[(None, '(Unknown)'), ('W', 'Weekday'), ('E', 'Weekend'), ('H', 'Holiday')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekDay',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'Monday'), (2, 'Thuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
        migrations.CreateModel(
            name='FixedScheduleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.IntegerField(choices=[(None, '(Unknown)'), (1, 'Monday'), (2, 'Thuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('startTime', models.TimeField()),
                ('duration', models.IntegerField()),
                ('dayType', models.CharField(choices=[(None, '(Unknown)'), ('W', 'Weekday'), ('E', 'Weekend'), ('H', 'Holiday')], max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.fixedschedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.teacher')),
            ],
        ),
    ]
